version: '3.8'


services:  

  client:
    container_name: client
    build:
      dockerfile: Dockerfile
      context: ./app
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
      - ./app:/app
      - /app/node_modules

 
